# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [84]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [85]:
data_file = "Output/fileOne.csv"
city_data = pd.read_csv(data_file)

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [123]:

 # Store latitude and longitude in locations
locations = city_data[["Lat", "Lng"]]

# Fill NaN values and convert to float
Humidity = city_data["Humidity"].astype(float)

In [129]:
fig = gmaps.figure(map_type="HYBRID")

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=Humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [95]:
vacation_df = city_data.loc[(city_data["Max Temp"] <= 300) & (city_data["Max Temp"] >= 295)
                            & (city_data["Cloudiness"] <= 50), :]

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
3,Mana,41,GF,1583104575,85,5.66,-53.78,295.89,1.30
12,Najrān,0,SA,1583104576,75,17.49,44.13,296.15,0.92
32,Bengkulu,38,ID,1583104578,91,-3.80,102.27,296.32,1.78
35,San Policarpo,8,PH,1583104578,76,12.18,125.51,299.38,5.34
42,Imbituba,20,BR,1583104578,83,-28.24,-48.67,297.15,3.60
...,...,...,...,...,...,...,...,...,...
542,Tahoua,44,NE,1583104644,12,14.89,5.27,298.75,4.12
549,Batié,2,BF,1583104646,13,9.88,-2.92,299.42,0.49
564,Road Town,20,VG,1583104647,74,18.42,-64.62,299.15,2.60
572,Mumford,11,GH,1583104648,84,5.26,-0.76,299.83,2.27
577,Presidencia Roque Sáenz Peña,0,AR,1583104648,39,-26.79,-60.44,297.55,1.66

In [101]:
vacation_df =vacation_df.dropna()
vacation_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
3,Mana,41,GF,1583104575,85,5.66,-53.78,295.89,1.30
12,Najrān,0,SA,1583104576,75,17.49,44.13,296.15,0.92
32,Bengkulu,38,ID,1583104578,91,-3.80,102.27,296.32,1.78
35,San Policarpo,8,PH,1583104578,76,12.18,125.51,299.38,5.34
42,Imbituba,20,BR,1583104578,83,-28.24,-48.67,297.15,3.60
...,...,...,...,...,...,...,...,...,...
542,Tahoua,44,NE,1583104644,12,14.89,5.27,298.75,4.12
549,Batié,2,BF,1583104646,13,9.88,-2.92,299.42,0.49
564,Road Town,20,VG,1583104647,74,18.42,-64.62,299.15,2.60
572,Mumford,11,GH,1583104648,84,5.26,-0.76,299.83,2.27
577,Presidencia Roque Sáenz Peña,0,AR,1583104648,39,-26.79,-60.44,297.55,1.66

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [105]:
hotel_df = vacation_df
hotel_df["Hotel Name"] = ""

In [106]:

#use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
    
    rowlat = row["Lat"]
    rowlng = row["Lng"]
    location = str(rowlat)+","+ str(rowlng)
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    params = {"location": {location},"radius":5000 ,"type": "hotel","key": g_key}
    print(params)
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {location}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
            print(f"Closest hotel is {results[0]['name']}.")

            hotel_df.loc[index, 'Hotel Name'] = response['results'][0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        print("------------")

{'location': {'5.66,-53.78'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 3: 5.66,-53.78.
Closest hotel is Mana.
{'location': {'17.49,44.13'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 12: 17.49,44.13.
Closest hotel is Najran.
{'location': {'-3.8,102.27'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 32: -3.8,102.27.
Closest hotel is Bengkulu.
{'location': {'12.18,125.51'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 35: 12.18,125.51.
Closest hotel is Oras.
{'location': {'-28.24,-48.67'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 42: -28.24,-48.67.
Closest hotel is Imbituba.
{'location': {'-13.7,-76.22'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 51: -13.7,-76.22.
Closest hotel is Pisco.
{'location': {'22.29,114.16'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 60: 22.29,114.16.
Closest hotel is Hong Kong.
{'location': {'17.02,54.09'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 80: 17.02,54.09.
Closest hotel is Salalah.
{'location': {'-33.02,27.91'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 84: -33.02,27.91.
Closest hotel is East London.
{'location': {'-20.28,44.28'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 94: -20.28,44.28.
Closest hotel is Morondava.
{'location': {'-40.81,-63.0'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 106: -40.81,-63.0.
Closest hotel is Viedma.
{'location': {'6.12,81.12'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 113: 6.12,81.12.
Closest hotel is Hambantota.
{'location': {'18.74,7.39'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 127: 18.74,7.39.
Closest hotel is Arlit.
{'location': {'10.62,104.18'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 166: 10.62,104.18.
Closest hotel is Krong Kampot.
{'location': {'22.68,-3.98'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 168: 22.68,-3.98.
Closest hotel is Taoudenni.
{'location': {'-24.87,113.63'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 174: -24.87,113.63.
Closest hotel is Carnarvon.
{'location': {'19.11,37.33'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 180: 19.11,37.33.
Closest hotel is Suakin.
{'location': {'11.92,109.16'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 204: 11.92,109.16.
Closest hotel is Cam Ranh.
{'location': {'-30.18,-50.21'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 205: -30.18,-50.21.
Closest hotel is CIDREIRA.
{'location': {'32.22,-98.2'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 210: 32.22,-98.2.
Closest hotel is Stephenville.
{'location': {'-11.32,-38.23'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 212: -11.32,-38.23.
Closest hotel is Itapicuru.
{'location': {'14.53,20.92'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 234: 14.53,20.92.
Closest hotel is Biltine.
{'location': {'-45.58,-72.07'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 246: -45.58,-72.07.
Closest hotel is Coyhaique.
{'location': {'-38.0,-57.56'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 251: -38.0,-57.56.
Closest hotel is Mar del Plata.
{'location': {'-13.2,49.05'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 255: -13.2,49.05.
Closest hotel is Ambilobe.
{'location': {'-32.03,-52.1'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 258: -32.03,-52.1.
Closest hotel is Rio Grande.
{'location': {'-28.87,153.57'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 259: -28.87,153.57.
Closest hotel is Ballina.
{'location': {'12.22,125.48'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 279: 12.22,125.48.
Closest hotel is San Policarpo.
{'location': {'25.21,64.64'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 296: 25.21,64.64.
Closest hotel is Ormara.
{'location': {'6.16,-0.55'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 304: 6.16,-0.55.
Closest hotel is Kyebi.
{'location': {'7.98,49.82'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 312: 7.98,49.82.
Closest hotel is Eyl.
{'location': {'3.94,41.87'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 320: 3.94,41.87.
Closest hotel is Mandera.
{'location': {'13.57,-15.6'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 326: 13.57,-15.6.
Closest hotel is Farafenni.
{'location': {'-20.58,48.53'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 332: -20.58,48.53.
Closest hotel is Nosy-Varika.
{'location': {'-8.19,114.97'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 338: -8.19,114.97.
Closest hotel is Banjar.
{'location': {'13.17,44.58'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 341: 13.17,44.58.
Missing field/result... skipping.
------------
{'location': {'22.24,68.97'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 345: 22.24,68.97.
Closest hotel is Dwarka.
{'location': {'-15.2,12.15'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 354: -15.2,12.15.
Closest hotel is Namibe.
{'location': {'-38.55,-58.74'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 366: -38.55,-58.74.
Closest hotel is Necochea.
{'location': {'4.88,-1.76'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 369: 4.88,-1.76.
Closest hotel is Takoradi.
{'location': {'5.35,48.53'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 398: 5.35,48.53.
Closest hotel is Hobyo.
{'location': {'4.09,30.68'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 399: 4.09,30.68.
Closest hotel is Yei.
{'location': {'-14.54,40.67'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 411: -14.54,40.67.
Closest hotel is Nacala.
{'location': {'19.9,77.58'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 418: 19.9,77.58.

Closest hotel is Pusad.
{'location': {'-1.5,33.8'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 423: -1.5,33.8.
Closest hotel is Musoma.
{'location': {'13.49,106.98'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 437: 13.49,106.98.
Closest hotel is Lumphat.
{'location': {'-14.45,-56.8'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 440: -14.45,-56.8.
Closest hotel is Nortelândia.
{'location': {'11.14,123.72'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 448: 11.14,123.72.
Closest hotel is Bantayan.
{'location': {'14.46,-4.92'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 461: 14.46,-4.92.
Closest hotel is Tenenkou.
{'location': {'27.94,-82.29'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 480: 27.94,-82.29.
Closest hotel is Brandon.
{'location': {'21.12,70.12'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 484: 21.12,70.12.
Closest hotel is Mangrol.
{'location': {'-11.96,-40.17'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 500: -11.96,-40.17.
Closest hotel is Baixa Grande.
{'location': {'-5.36,104.97'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 514: -5.36,104.97.
Closest hotel is Margakaja.
{'location': {'-6.37,-44.36'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 528: -6.37,-44.36.
Closest hotel is Mirador.
{'location': {'13.32,12.61'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 529: 13.32,12.61.
Closest hotel is Diffa.
{'location': {'4.87,-2.24'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 533: 4.87,-2.24.
Closest hotel is Axim.
{'location': {'14.89,5.27'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 542: 14.89,5.27.
Closest hotel is Tahoua.
{'location': {'9.88,-2.92'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 549: 9.88,-2.92.
Closest hotel is Batie.
{'location': {'18.42,-64.62'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 564: 18.42,-64.62.
Closest hotel is Road Town.
{'location': {'5.26,-0.76'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 572: 5.26,-0.76.
Closest hotel is Apam.
{'location': {'-26.79,-60.44'}, 'radius': 5000, 'type': 'hotel', 'key': 'AIzaSyAptUoKwNEYBGAqMFKIau8m6dF5PZvvdyQ'}
Retrieving Results for Index 577: -26.79,-60.44.
Closest hotel is Presidencia Roque Sáenz Peña.

In [116]:
hotel_df.reset_index
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
3,Mana,41,GF,1583104575,85,5.66,-53.78,295.89,1.30,Mana
12,Najrān,0,SA,1583104576,75,17.49,44.13,296.15,0.92,Najran
32,Bengkulu,38,ID,1583104578,91,-3.80,102.27,296.32,1.78,Bengkulu
35,San Policarpo,8,PH,1583104578,76,12.18,125.51,299.38,5.34,Oras
42,Imbituba,20,BR,1583104578,83,-28.24,-48.67,297.15,3.60,Imbituba
...,...,...,...,...,...,...,...,...,...,...
542,Tahoua,44,NE,1583104644,12,14.89,5.27,298.75,4.12,Tahoua
549,Batié,2,BF,1583104646,13,9.88,-2.92,299.42,0.49,Batie
564,Road Town,20,VG,1583104647,74,18.42,-64.62,299.15,2.60,Road Town
572,Mumford,11,GH,1583104648,84,5.26,-0.76,299.83,2.27,Apam
577,Presidencia Roque Sáenz Peña,0,AR,1583104648,39,-26.79,-60.44,297.55,1.66,Presidencia Roque Sáenz Peña

In [110]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [120]:
# Add marker layer ontop of heat map

symbols = gmaps.symbol_layer(locations, fill_color='red', stroke_color='red')
fig.add_layer(symbols)
# Display Map
fig

Figure(layout=FigureLayout(height='420px'))